version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "monthly"
        time: "09:00"
        timezone: "Europe/Paris"
      labels:
      - "dependencies"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "monthly"
        time: "09:00"
        timezone: "Europe/Paris"
      labels:
      - "dependencies"
